name: Tests

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

defaults:
  run:
    working-directory: ./ui-plugin

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'Build'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: './ui-plugin/.nvmrc'
          cache: 'yarn'
          cache-dependency-path: './ui-plugin/yarn.lock'

      - name: Install dependencies
        run: yarn

      - name: Lint the sources
        run: yarn lint

      - name: Build the Neos UI plugin
        run: yarn build
